<footer class="bottom-bar">
    <div class="newsletter-signup">
        <div class="container-default email-form">
            <div class="half">
                <h6>Get notified about printing tips, sales, new products, and events</h6>
            </div>
            <div class="half">
                <div id="gform_wrapper_1" class="gf_browser_unknown gform_wrapper">
                    <div id="gf_1" class="gform_anchor" tabindex="-1">&nbsp;</div>
                    <form id="gform_1" action="/#gf_1" enctype="multipart/form-data" method="post" target="gform_ajax_frame_1" data-formtitle="News Signup">
                        <div class="gform_body">
                            <ul id="gform_fields_1" class="gform_fields top_label form_sublabel_below description_below">
                                <li id="field_1_1" class="gfield gfield_contains_required field_sublabel_below field_description_below gfield_visibility_visible"><label class="gfield_label" for="input_1_1">Email<span class="gfield_required">*</span></label>
                                    <div class="ginput_container ginput_container_email"><input id="input_1_1" class="medium" tabindex="100" name="input_1" type="email" value="" placeholder="Email" aria-required="true" aria-invalid="false"></div>
                                </li>
                                <li id="field_1_2" class="gfield gform_validation_container field_sublabel_below field_description_below gfield_visibility_visible"><label class="gfield_label" for="input_1_2">Phone</label>
                                    <div class="ginput_container"><input id="input_1_2" autocomplete="off" name="input_2" type="text" value=""></div>
                                    <div id="gfield_description_1_2" class="gfield_description">This field is for validation purposes and should be left unchanged.</div>
                                </li>
                            </ul>
                        </div>
                        <div class="gform_footer top_label"><button id="gform_submit_button_1" class="gform_button button" tabindex="101" type="submit" value="Get Notified">Get Notified</button> <input name="gform_ajax" type="hidden" value="form_id=1&amp;title=&amp;description=&amp;tabindex=100"> <input class="gform_hidden" name="is_submit_1" type="hidden" value="1"> <input class="gform_hidden" name="gform_submit" type="hidden" value="1"> <input class="gform_hidden" name="gform_unique_id" type="hidden" value=""> <input class="gform_hidden" name="state_1" type="hidden" value="WyJbXSIsIjRiMTNjMTg3ODEyOTZmYmE4NThhNzRlODExOTI3YjVlIl0="> <input id="gform_target_page_number_1" class="gform_hidden" name="gform_target_page_number_1" type="hidden" value="0"> <input id="gform_source_page_number_1" class="gform_hidden" name="gform_source_page_number_1" type="hidden" value="1"> <input name="gform_field_values" type="hidden" value=""></div>
                    </form></div>
                <iframe id="gform_ajax_frame_1" style="display: none; width: 0px; height: 0px;" title="This iframe contains the logic required to handle Ajax powered Gravity Forms." src="about:blank" name="gform_ajax_frame_1"></iframe></div>
        </div>
    </div>
    <div class="footer-info">
        <div class="container-default">
            <div class="footer-nav">
                <div class="menu-new-footer-menu-container">
                    <ul id="menu-new-footer-menu" class="menu">
                        <li class="menu-item menu-item-top-level menu-item-has-children" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers.html">Printers by Brand</a> <button class="sub-menu-toggle" aria-label="Toggle Sub-menu Item" aria-expanded="false"></button>
                            <ul class="sub-menu sub-menu-level-1" role="menu" aria-hidden="true">
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers/mimaki.html">Mimaki</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers/mutoh.html">Mutoh</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers/epson.html">Epson</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers/efi.html">EFI</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-top-level menu-item-has-children" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category.html">Printers by Category</a> <button class="sub-menu-toggle" aria-label="Toggle Sub-menu Item" aria-expanded="false"></button>
                            <ul class="sub-menu sub-menu-level-1" role="menu" aria-hidden="true">
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/industries-solutions/direct-to-garment-printer/">Direct to Garment (DTG) Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/blog/large-format-flatbed-printer/">Flatbed Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category/roll-to-roll.html">Roll-to-Roll Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category/roll-to-roll/dye-sublimation.html">Dye Sublimation Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category/roll-to-roll/direct-to-textile.html">Direct to Textile Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category/roll-to-roll/solvent.html">Solvent Printers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/printers-by-category/roll-to-roll/uv.html">UV Printers</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-top-level menu-item-has-children" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-brand.html">Inks &amp; Primers by Brand</a> <button class="sub-menu-toggle" aria-label="Toggle Sub-menu Item" aria-expanded="false"></button>
                            <ul class="sub-menu sub-menu-level-1" role="menu" aria-hidden="true">
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-brand/mimaki.html">Mimaki Inks &amp; Primers</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-brand/epson.html">Epson Inks &amp; Primers</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-top-level menu-item-has-children" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category.html">Inks &amp; Primers by Category</a> <button class="sub-menu-toggle" aria-label="Toggle Sub-menu Item" aria-expanded="false"></button>
                            <ul class="sub-menu sub-menu-level-1" role="menu" aria-hidden="true">
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category/uv.html">UV Inks</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category/solvent.html">Solvent Inks</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category/textile.html">Textile Inks</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category/inks.html">Fine Art &amp; Photo Inks</a></li>
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/store/inks-by-category/other.html">Primers</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-top-level menu-item-has-children" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/authorized-mimaki-dealer-distributor/">Partners</a> <button class="sub-menu-toggle" aria-label="Toggle Sub-menu Item" aria-expanded="false"></button>
                            <ul class="sub-menu sub-menu-level-1" role="menu" aria-hidden="true">
                                <li class="menu-item menu-item-level-2" role="menuitem" aria-haspopup="true"><a class="menu-item-link" href="http://itnh.local/authorized-mimaki-dealer-distributor/">ITNH and Mimaki</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <p>© 2021 ITNH. All rights reserved. <a href="http://itnh.local/terms-conditions/">Terms &amp; Conditions</a></p>
                <p><strong>** ITNH is An Equal Opportunity Employer **</strong></p>
                <p>&nbsp;</p>
            </div>
            <div class="footer-support">
                <div>
                    <div class="icon icon-sales" data-grunticon-embed="">&nbsp;</div>
                    <h5>Sales</h5>
                    <a href="tel:866.465.5387">866.465.5387</a></div>
                <div>
                    <div class="icon icon-support" data-grunticon-embed="">&nbsp;</div>
                    <h5>Support</h5>
                    <a href="tel:603.669.6900">603.669.6900</a></div>
                <strong>Hours: </strong>Corporate Office Hours are M-F 8:00-5:00 EST, Service Hours 8:00-8:00 EST
                <div class="social"><a href="https://twitter.com/ITNHPrinting" target="_blank" rel="noopener"> <span class="icon icon-twitter" data-grunticon-embed=""> <span class="screen-reader-text">Twitter</span> </span> </a> <a href="https://www.facebook.com/ITNHPrinting/?fref=ts" target="_blank" rel="noopener"> <span class="icon icon-facebook" data-grunticon-embed=""> <span class="screen-reader-text">Facebook</span> </span> </a> <a href="https://www.linkedin.com/company/1338702" target="_blank" rel="noopener"> <span class="icon icon-linkedin" data-grunticon-embed=""> <span class="screen-reader-text">LinkedIn</span> </span> </a></div>
            </div>
        </div>
    </div>
</footer>
