<div class="menu">
    <div class="menu__column">
        <h4><?php echo __('First Tilte')?></h4>
        <ul>
            <li><a href="#"><?php echo __('Customer Sevice')?></a></li>
            <li><a href="#"><?php echo __('Faq')?></a></li>
            <li><a href="#"><?php echo __('Shipping Information')?></a></li>
            <li><a href="#"><?php echo __('Site terms & Conditions')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Second Tilte')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('About Us')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Privacy Policy')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Contact Us')?>"><?php echo __('Contact Us')?></a></li>
        </ul>
    </div>
</div>
