<header class="top-bar">
    <div class="top-container">
        <div class="nav-utility">
            <div class="menu-utility-menu-container">
                <ul id="menu-utility-menu" class="menu">
                    <li>
                        Sales: <a class="telephone" href="tel:866.465.5387">866.465.5387</a>
                    </li>
                    <li>
                        <a href="http://itnh.local/request-a-quote">Request a Quote</a>
                    </li>
                    <li class="icon icon-cart-white menu-item menu-item-top-level">
                        <a href="http://itnh.local/store/checkout/cart/">
                        </a>
                    </li>
                    <li class="icon icon-contact-white menu-item menu-item-top-level" role="menuitem"
                        aria-haspopup="true"><a class="menu-item-link" href="#">Customer Support</a>
                        <div class="header-support">
                            <div>
                                <i class="icon icon-sales" data-grunticon-embed></i>
                                <span>
                                    <h5>Sales</h5>
                                    <a href="tel:866.465.5387">866.465.5387</a>
                                </span>
                            </div>
                            <div>
                                <i class="icon icon-support" data-grunticon-embed></i>
                                <span>
                                    <h5>Support</h5>
                                    <a href="tel:603.669.6900">603.669.6900</a>
                                </span>
                            </div>
                            <div>
                                <i class="icon icon-chat" data-grunticon-embed></i>
                                <span>
                                    <h5>Chat</h5>
                                </span>
                            </div>
                        </div>
                    </li>
                    <li class="icon icon-login-white menu-item menu-item-top-level" role="menuitem"
                        aria-haspopup="true"><a class="menu-item-link" href="#">Login</a>
                        <div class="header-login">
                            <div>
                                <form action="http://itnh.local/store/customer/account/loginPost/" method="post">
                                    <input type="hidden" value="SqzavmauQrgF972F" name="form_key">
                                    <input type="email" placeholder="Username" autocapitalize="off" autocorrect="off"
                                           spellcheck="false" name="login[username]" value="" id="email"
                                           class="required-entry validate-email">
                                    <input type="password" placeholder="Password" name="login[password]"
                                           class="required-entry validate-password" id="pass">
                                    <button class="button-white" type="submit">Login</button>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
</header>
